# file path to the spreadsheet with media URLs
links_spreadsheet_path: C:\Users\NicholasLabrie\OneDrive\OneDrive - ausohio.com\bell\links.xlsx

# file path to where the logger logs to
log_file_path: C:\Users\NicholasLabrie\OneDrive\OneDrive - ausohio.com\bell\bell.log

# times can be added/subtracted to the bell schedule
# always use 24h hour time format
bell_schedule:
  - hour: 9
    minute: 15
  - hour: 10
    minute: 12
  - hour: 11
    minute: 15
  - hour: 12
    minute: 12
  - hour: 13
    minute: 42
  - hour: 14
    minute: 42
  - hour: 15
    minute: 40
