# file path to the spreadsheet with media URLs
links_spreadsheet_path: C:\Users\NicholasLabrie\OneDrive\OneDrive - ausohio.com\bell\links.xlsx

# file path to where the logger logs to
log_file_path: C:\Users\NicholasLabrie\OneDrive\OneDrive - ausohio.com\bell\bell.log

# times can be added/subtracted to the bell schedule
# always use 24h hour time format
# always use HH:MM hour time format
bell_schedule:
  - "09:15"
  - "10:12"
  - "11:15"
  - "12:12"
  - "13:42"
  - "14:42"
  - "15:40"
